// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Screen1Cercle;
lv_obj_t * ui_LabelTempScreen1;
lv_obj_t * ui_LabelTempCScreen1;
lv_obj_t * ui_LabelTimeScreen1;
lv_obj_t * ui_LabelDateScreen1;
lv_obj_t * ui_LabelHumScreen1;
lv_obj_t * ui_Screen1Point1;
lv_obj_t * ui_Screen1Point2;
lv_obj_t * ui_Screen1Point3;
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Screen1Point4;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen1;
lv_obj_t * uic_Screen1Cercle;
lv_obj_t * uic_LabelTempScreen1;
lv_obj_t * uic_LabelTempCScreen1;
lv_obj_t * uic_LabelTimeScreen1;
lv_obj_t * uic_LabelDateScreen1;
lv_obj_t * uic_LabelHumScreen1;
lv_obj_t * uic_Screen1Point1;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Screen1Cercle1;
lv_obj_t * ui_LabelKmHScreen2;
lv_obj_t * ui_LabelPasScreen2;
lv_obj_t * ui_Screen2Point2;
lv_obj_t * ui_Screen2Point1;
lv_obj_t * ui_Screen2Point3;
lv_obj_t * ui_LabelKmH2Screen2;
lv_obj_t * ui_LabelPas2Screen2;
lv_obj_t * ui_LabelTimeScreen3;
lv_obj_t * ui_Screen2Point4;
// CUSTOM VARIABLES
lv_obj_t * uic_LabelKmHScreen2;
lv_obj_t * uic_LabelPasScreen2;
lv_obj_t * uic_Screen2Point2;
lv_obj_t * uic_Screen2Point1;
lv_obj_t * uic_Screen2Point3;
lv_obj_t * uic_LabelKmH2Screen2;
lv_obj_t * uic_LabelPas2Screen2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_Screen1Cercle2;
lv_obj_t * ui_LabelGyroScreen3;
lv_obj_t * ui_Screen3Point2;
lv_obj_t * ui_Screen3Point1;
lv_obj_t * ui_Screen3Point3;
lv_obj_t * ui_LabelGyro2Screen3;
lv_obj_t * ui_LabelSudScreen3;
lv_obj_t * ui_LabelTimeScreen4;
lv_obj_t * ui_Screen3Point7;
// CUSTOM VARIABLES
lv_obj_t * uic_LabelGyroScreen3;
lv_obj_t * uic_Screen3Point2;
lv_obj_t * uic_Screen3Point1;
lv_obj_t * uic_Screen3Point3;
lv_obj_t * uic_LabelGyro2Screen3;
lv_obj_t * uic_LabelSudScreen3;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
lv_obj_t * ui_Screen1Cercle3;
lv_obj_t * ui_LabelHeureScreen5;
lv_obj_t * ui_LabelHeure2Screen5;
lv_obj_t * ui_LabelMinuteScreen5;
lv_obj_t * ui_LabelSecondeScreen5;
lv_obj_t * ui_LabelHeure2Screen1;
lv_obj_t * ui_LabelJourScreen5;
lv_obj_t * ui_LabelJour2Screen4;
lv_obj_t * ui_LabelMoisScreen5;
lv_obj_t * ui_LabelMois2Screen4;
lv_obj_t * ui_LabelAnneeScreen5;
lv_obj_t * ui_ButtonPlusHeure;
lv_obj_t * ui_LabelTimeScreen5;
lv_obj_t * ui_ButtonPlusMinute;
lv_obj_t * ui_ButtonPlusSeconde;
lv_obj_t * ui_ButtonMoinsHeure;
lv_obj_t * ui_ButtonMoinsMinute;
lv_obj_t * ui_ButtonMoinsSeconde;
lv_obj_t * ui_ButtonPlusJour;
lv_obj_t * ui_ButtonPlusMois;
lv_obj_t * ui_ButtonPlusAnnee;
lv_obj_t * ui_ButtonMoinsJour;
lv_obj_t * ui_ButtonMoinsMois;
lv_obj_t * ui_ButtonMoinsAnnee;
lv_obj_t * ui_Plus1;
lv_obj_t * ui_Plus2;
lv_obj_t * ui_Plus3;
lv_obj_t * ui_Plus4;
lv_obj_t * ui_Plus5;
lv_obj_t * ui_Plus6;
lv_obj_t * ui_Moins1;
lv_obj_t * ui_Moins2;
lv_obj_t * ui_Moins3;
lv_obj_t * ui_Moins4;
lv_obj_t * ui_Moins5;
lv_obj_t * ui_Moins6;
lv_obj_t * ui_Button4;
lv_obj_t * ui_Image7;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen5;
lv_obj_t * uic_LabelHeureScreen5;
lv_obj_t * uic_LabelHeure2Screen5;
lv_obj_t * uic_LabelMinuteScreen5;
lv_obj_t * uic_LabelSecondeScreen5;
lv_obj_t * uic_LabelHeure2Screen1;
lv_obj_t * uic_LabelJourScreen5;
lv_obj_t * uic_LabelJour2Screen4;
lv_obj_t * uic_LabelMoisScreen5;
lv_obj_t * uic_LabelMois2Screen4;
lv_obj_t * uic_LabelAnneeScreen5;
lv_obj_t * uic_ButtonPlusHeure;
lv_obj_t * uic_ButtonPlusMinute;
lv_obj_t * uic_ButtonPlusSeconde;
lv_obj_t * uic_ButtonMoinsHeure;
lv_obj_t * uic_ButtonMoinsMinute;
lv_obj_t * uic_ButtonMoinsSeconde;
lv_obj_t * uic_ButtonPlusJour;
lv_obj_t * uic_ButtonPlusMois;
lv_obj_t * uic_ButtonPlusAnnee;
lv_obj_t * uic_ButtonMoinsJour;
lv_obj_t * uic_ButtonMoinsMois;
lv_obj_t * uic_ButtonMoinsAnnee;
lv_obj_t * uic_Plus1;
lv_obj_t * uic_Moins1;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_Screen1Cercle4;
lv_obj_t * ui_LabelChronoScreen4;
lv_obj_t * ui_Screen3Point4;
lv_obj_t * ui_Screen3Point5;
lv_obj_t * ui_Screen3Point6;
lv_obj_t * ui_LabelChronometreScreen4;
lv_obj_t * ui_Screen3Point8;
lv_obj_t * ui_LabelChronoScreen1;
lv_obj_t * ui_LabelChronoScreen2;
lv_obj_t * ui_LabelChronoScreen3;
lv_obj_t * ui_LabelChronoScreen5;
lv_obj_t * ui_ButtonSTART;
lv_obj_t * ui_ButtonRESET;
lv_obj_t * ui_LabelRESET;
lv_obj_t * ui_ButtonSTOP;
lv_obj_t * ui_LabelSTART;
lv_obj_t * ui_LabelSTOP;
// CUSTOM VARIABLES
lv_obj_t * uic_LabelChronoScreen4;
lv_obj_t * uic_LabelChronometreScreen4;
lv_obj_t * uic_ButtonSTART;
lv_obj_t * uic_ButtonSTOP;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen5_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
