// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#ifndef _LED_SWITCH___COPIE_UI_H
#define _LED_SWITCH___COPIE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1Cercle;
extern lv_obj_t * ui_LabelTempScreen1;
extern lv_obj_t * ui_LabelTempCScreen1;
extern lv_obj_t * ui_LabelTimeScreen1;
extern lv_obj_t * ui_LabelDateScreen1;
extern lv_obj_t * ui_LabelHumScreen1;
extern lv_obj_t * ui_Screen1Point1;
extern lv_obj_t * ui_Screen1Point2;
extern lv_obj_t * ui_Screen1Point3;
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Screen1Point4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Screen1Cercle;
extern lv_obj_t * uic_LabelTempScreen1;
extern lv_obj_t * uic_LabelTempCScreen1;
extern lv_obj_t * uic_LabelTimeScreen1;
extern lv_obj_t * uic_LabelDateScreen1;
extern lv_obj_t * uic_LabelHumScreen1;
extern lv_obj_t * uic_Screen1Point1;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Screen1Cercle1;
extern lv_obj_t * ui_LabelKmHScreen2;
extern lv_obj_t * ui_LabelPasScreen2;
extern lv_obj_t * ui_Screen2Point2;
extern lv_obj_t * ui_Screen2Point1;
extern lv_obj_t * ui_Screen2Point3;
extern lv_obj_t * ui_LabelKmH2Screen2;
extern lv_obj_t * ui_LabelPas2Screen2;
extern lv_obj_t * ui_LabelTimeScreen3;
extern lv_obj_t * ui_Screen2Point4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LabelKmHScreen2;
extern lv_obj_t * uic_LabelPasScreen2;
extern lv_obj_t * uic_Screen2Point2;
extern lv_obj_t * uic_Screen2Point1;
extern lv_obj_t * uic_Screen2Point3;
extern lv_obj_t * uic_LabelKmH2Screen2;
extern lv_obj_t * uic_LabelPas2Screen2;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Screen1Cercle2;
extern lv_obj_t * ui_LabelGyroScreen3;
extern lv_obj_t * ui_Screen3Point2;
extern lv_obj_t * ui_Screen3Point1;
extern lv_obj_t * ui_Screen3Point3;
extern lv_obj_t * ui_LabelGyro2Screen3;
extern lv_obj_t * ui_LabelSudScreen3;
extern lv_obj_t * ui_LabelTimeScreen4;
extern lv_obj_t * ui_Screen3Point7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LabelGyroScreen3;
extern lv_obj_t * uic_Screen3Point2;
extern lv_obj_t * uic_Screen3Point1;
extern lv_obj_t * uic_Screen3Point3;
extern lv_obj_t * uic_LabelGyro2Screen3;
extern lv_obj_t * uic_LabelSudScreen3;

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Screen1Cercle3;
extern lv_obj_t * ui_LabelHeureScreen5;
extern lv_obj_t * ui_LabelHeure2Screen5;
extern lv_obj_t * ui_LabelMinuteScreen5;
extern lv_obj_t * ui_LabelSecondeScreen5;
extern lv_obj_t * ui_LabelHeure2Screen1;
extern lv_obj_t * ui_LabelJourScreen5;
extern lv_obj_t * ui_LabelJour2Screen4;
extern lv_obj_t * ui_LabelMoisScreen5;
extern lv_obj_t * ui_LabelMois2Screen4;
extern lv_obj_t * ui_LabelAnneeScreen5;
extern lv_obj_t * ui_ButtonPlusHeure;
extern lv_obj_t * ui_LabelTimeScreen5;
extern lv_obj_t * ui_ButtonPlusMinute;
extern lv_obj_t * ui_ButtonPlusSeconde;
extern lv_obj_t * ui_ButtonMoinsHeure;
extern lv_obj_t * ui_ButtonMoinsMinute;
extern lv_obj_t * ui_ButtonMoinsSeconde;
extern lv_obj_t * ui_ButtonPlusJour;
extern lv_obj_t * ui_ButtonPlusMois;
extern lv_obj_t * ui_ButtonPlusAnnee;
extern lv_obj_t * ui_ButtonMoinsJour;
extern lv_obj_t * ui_ButtonMoinsMois;
extern lv_obj_t * ui_ButtonMoinsAnnee;
extern lv_obj_t * ui_Plus1;
extern lv_obj_t * ui_Plus2;
extern lv_obj_t * ui_Plus3;
extern lv_obj_t * ui_Plus4;
extern lv_obj_t * ui_Plus5;
extern lv_obj_t * ui_Plus6;
extern lv_obj_t * ui_Moins1;
extern lv_obj_t * ui_Moins2;
extern lv_obj_t * ui_Moins3;
extern lv_obj_t * ui_Moins4;
extern lv_obj_t * ui_Moins5;
extern lv_obj_t * ui_Moins6;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen5;
extern lv_obj_t * uic_LabelHeureScreen5;
extern lv_obj_t * uic_LabelHeure2Screen5;
extern lv_obj_t * uic_LabelMinuteScreen5;
extern lv_obj_t * uic_LabelSecondeScreen5;
extern lv_obj_t * uic_LabelHeure2Screen1;
extern lv_obj_t * uic_LabelJourScreen5;
extern lv_obj_t * uic_LabelJour2Screen4;
extern lv_obj_t * uic_LabelMoisScreen5;
extern lv_obj_t * uic_LabelMois2Screen4;
extern lv_obj_t * uic_LabelAnneeScreen5;
extern lv_obj_t * uic_ButtonPlusHeure;
extern lv_obj_t * uic_ButtonPlusMinute;
extern lv_obj_t * uic_ButtonPlusSeconde;
extern lv_obj_t * uic_ButtonMoinsHeure;
extern lv_obj_t * uic_ButtonMoinsMinute;
extern lv_obj_t * uic_ButtonMoinsSeconde;
extern lv_obj_t * uic_ButtonPlusJour;
extern lv_obj_t * uic_ButtonPlusMois;
extern lv_obj_t * uic_ButtonPlusAnnee;
extern lv_obj_t * uic_ButtonMoinsJour;
extern lv_obj_t * uic_ButtonMoinsMois;
extern lv_obj_t * uic_ButtonMoinsAnnee;
extern lv_obj_t * uic_Plus1;
extern lv_obj_t * uic_Moins1;

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Screen1Cercle4;
extern lv_obj_t * ui_LabelChronoScreen4;
extern lv_obj_t * ui_Screen3Point4;
extern lv_obj_t * ui_Screen3Point5;
extern lv_obj_t * ui_Screen3Point6;
extern lv_obj_t * ui_LabelChronometreScreen4;
extern lv_obj_t * ui_Screen3Point8;
extern lv_obj_t * ui_LabelChronoScreen1;
extern lv_obj_t * ui_LabelChronoScreen2;
extern lv_obj_t * ui_LabelChronoScreen3;
extern lv_obj_t * ui_LabelChronoScreen5;
extern lv_obj_t * ui_ButtonSTART;
extern lv_obj_t * ui_ButtonRESET;
extern lv_obj_t * ui_LabelRESET;
extern lv_obj_t * ui_ButtonSTOP;
extern lv_obj_t * ui_LabelSTART;
extern lv_obj_t * ui_LabelSTOP;
// CUSTOM VARIABLES
extern lv_obj_t * uic_LabelChronoScreen4;
extern lv_obj_t * uic_LabelChronometreScreen4;
extern lv_obj_t * uic_ButtonSTART;
extern lv_obj_t * uic_ButtonSTOP;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_parametre1_30x30_png);    // assets/Parametre1_30x30.png
LV_IMG_DECLARE(ui_img_1270785427);    // assets/icons8-accueil-24.png

// FONTS
LV_FONT_DECLARE(ui_font_SFPRO16);
LV_FONT_DECLARE(ui_font_SFPRO18);
LV_FONT_DECLARE(ui_font_SFPRO20);
LV_FONT_DECLARE(ui_font_SFPRO25);
LV_FONT_DECLARE(ui_font_SFPRO30);
LV_FONT_DECLARE(ui_font_SFPRO40);
LV_FONT_DECLARE(ui_font_SFPRO48);
LV_FONT_DECLARE(ui_font_SFPRO72);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
