// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Cercle2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen1Cercle2, 240);
    lv_obj_set_height(ui_Screen1Cercle2, 240);
    lv_obj_set_align(ui_Screen1Cercle2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Cercle2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Cercle2, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Cercle2, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Cercle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGyroScreen3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelGyroScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGyroScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelGyroScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGyroScreen3, "180");
    lv_obj_set_style_text_color(ui_LabelGyroScreen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGyroScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGyroScreen3, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3Point2, 10);
    lv_obj_set_height(ui_Screen3Point2, 10);
    lv_obj_set_x(ui_Screen3Point2, 15);
    lv_obj_set_y(ui_Screen3Point2, 90);
    lv_obj_set_align(ui_Screen3Point2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3Point1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3Point1, 10);
    lv_obj_set_height(ui_Screen3Point1, 10);
    lv_obj_set_x(ui_Screen3Point1, -45);
    lv_obj_set_y(ui_Screen3Point1, 90);
    lv_obj_set_align(ui_Screen3Point1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3Point3, 10);
    lv_obj_set_height(ui_Screen3Point3, 10);
    lv_obj_set_x(ui_Screen3Point3, -15);
    lv_obj_set_y(ui_Screen3Point3, 90);
    lv_obj_set_align(ui_Screen3Point3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGyro2Screen3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelGyro2Screen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGyro2Screen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGyro2Screen3, 55);
    lv_obj_set_y(ui_LabelGyro2Screen3, -12);
    lv_obj_set_align(ui_LabelGyro2Screen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGyro2Screen3, "°");
    lv_obj_set_style_text_color(ui_LabelGyro2Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelGyro2Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelGyro2Screen3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSudScreen3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelSudScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSudScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSudScreen3, 0);
    lv_obj_set_y(ui_LabelSudScreen3, 45);
    lv_obj_set_align(ui_LabelSudScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSudScreen3, "Sud");
    lv_obj_set_style_text_color(ui_LabelSudScreen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSudScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSudScreen3, &ui_font_SFPRO18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeScreen4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelTimeScreen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen4, 0);
    lv_obj_set_y(ui_LabelTimeScreen4, -100);
    lv_obj_set_align(ui_LabelTimeScreen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen4, "15:08");
    lv_obj_set_style_text_color(ui_LabelTimeScreen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimeScreen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimeScreen4, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point7 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Screen3Point7, 10);
    lv_obj_set_height(ui_Screen3Point7, 10);
    lv_obj_set_x(ui_Screen3Point7, 45);
    lv_obj_set_y(ui_Screen3Point7, 90);
    lv_obj_set_align(ui_Screen3Point7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point7, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_LabelGyroScreen3 = ui_LabelGyroScreen3;
    uic_Screen3Point2 = ui_Screen3Point2;
    uic_Screen3Point1 = ui_Screen3Point1;
    uic_Screen3Point3 = ui_Screen3Point3;
    uic_LabelGyro2Screen3 = ui_LabelGyro2Screen3;
    uic_LabelSudScreen3 = ui_LabelSudScreen3;

}
