// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "../ui.h"
#include "chrono.h"

// Callbacks des boutons
void start_btn_cb(lv_event_t * e) {
    chrono_start();
}

void stop_btn_cb(lv_event_t * e) {
    chrono_stop();
}

void reset_btn_cb(lv_event_t * e) {
    chrono_reset();
}


void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Cercle4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Screen1Cercle4, 240);
    lv_obj_set_height(ui_Screen1Cercle4, 240);
    lv_obj_set_align(ui_Screen1Cercle4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Cercle4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Cercle4, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Cercle4, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Cercle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronoScreen4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronoScreen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronoScreen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelChronoScreen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronoScreen4, "00");
    lv_obj_set_style_text_color(ui_LabelChronoScreen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronoScreen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronoScreen4, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point4 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Screen3Point4, 10);
    lv_obj_set_height(ui_Screen3Point4, 10);
    lv_obj_set_x(ui_Screen3Point4, 45);
    lv_obj_set_y(ui_Screen3Point4, 90);
    lv_obj_set_align(ui_Screen3Point4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen3Point5 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Screen3Point5, 10);
    lv_obj_set_height(ui_Screen3Point5, 10);
    lv_obj_set_x(ui_Screen3Point5, -45);
    lv_obj_set_y(ui_Screen3Point5, 90);
    lv_obj_set_align(ui_Screen3Point5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point5, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point6 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Screen3Point6, 10);
    lv_obj_set_height(ui_Screen3Point6, 10);
    lv_obj_set_x(ui_Screen3Point6, -15);
    lv_obj_set_y(ui_Screen3Point6, 90);
    lv_obj_set_align(ui_Screen3Point6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point6, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronometreScreen4 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronometreScreen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronometreScreen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChronometreScreen4, 0);
    lv_obj_set_y(ui_LabelChronometreScreen4, -69);
    lv_obj_set_align(ui_LabelChronometreScreen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronometreScreen4, "CHRONOMETRE");
    lv_obj_set_style_text_color(ui_LabelChronometreScreen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronometreScreen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronometreScreen4, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen3Point8 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Screen3Point8, 10);
    lv_obj_set_height(ui_Screen3Point8, 10);
    lv_obj_set_x(ui_Screen3Point8, 15);
    lv_obj_set_y(ui_Screen3Point8, 90);
    lv_obj_set_align(ui_Screen3Point8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen3Point8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3Point8, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3Point8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronoScreen1 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronoScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronoScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChronoScreen1, -70);
    lv_obj_set_y(ui_LabelChronoScreen1, 0);
    lv_obj_set_align(ui_LabelChronoScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronoScreen1, "00");
    lv_obj_set_style_text_color(ui_LabelChronoScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronoScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronoScreen1, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronoScreen2 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronoScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronoScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChronoScreen2, 70);
    lv_obj_set_y(ui_LabelChronoScreen2, 0);
    lv_obj_set_align(ui_LabelChronoScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronoScreen2, "00");
    lv_obj_set_style_text_color(ui_LabelChronoScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronoScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronoScreen2, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronoScreen3 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronoScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronoScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChronoScreen3, 35);
    lv_obj_set_y(ui_LabelChronoScreen3, -3);
    lv_obj_set_align(ui_LabelChronoScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronoScreen3, ":");
    lv_obj_set_style_text_color(ui_LabelChronoScreen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronoScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronoScreen3, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChronoScreen5 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelChronoScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChronoScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChronoScreen5, -35);
    lv_obj_set_y(ui_LabelChronoScreen5, -3);
    lv_obj_set_align(ui_LabelChronoScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChronoScreen5, ":");
    lv_obj_set_style_text_color(ui_LabelChronoScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChronoScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChronoScreen5, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSTART = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonSTART, 50);
    lv_obj_set_height(ui_ButtonSTART, 35);
    lv_obj_set_x(ui_ButtonSTART, -60);
    lv_obj_set_y(ui_ButtonSTART, 45);
    lv_obj_set_align(ui_ButtonSTART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSTART, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSTART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSTART, lv_color_hex(0x008404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonSTART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonSTART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRESET = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonRESET, 50);
    lv_obj_set_height(ui_ButtonRESET, 35);
    lv_obj_set_x(ui_ButtonRESET, 60);
    lv_obj_set_y(ui_ButtonRESET, 45);
    lv_obj_set_align(ui_ButtonRESET, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRESET, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRESET, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonRESET, lv_color_hex(0x003E6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonRESET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonRESET, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonRESET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_LabelRESET = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelRESET, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRESET, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRESET, 60);
    lv_obj_set_y(ui_LabelRESET, 45);
    lv_obj_set_align(ui_LabelRESET, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRESET, "RESET");
    lv_obj_set_style_text_color(ui_LabelRESET, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRESET, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_ButtonSTOP = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_ButtonSTOP, 50);
    lv_obj_set_height(ui_ButtonSTOP, 35);
    lv_obj_set_x(ui_ButtonSTOP, 0);
    lv_obj_set_y(ui_ButtonSTOP, 45);
    lv_obj_set_align(ui_ButtonSTOP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSTOP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSTOP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonSTOP, lv_color_hex(0x840000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSTOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonSTOP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonSTOP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ButtonSTOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSTART = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelSTART, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSTART, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSTART, -60);
    lv_obj_set_y(ui_LabelSTART, 45);
    lv_obj_set_align(ui_LabelSTART, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSTART, "START");
    lv_obj_set_style_text_color(ui_LabelSTART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSTART, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSTOP = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_LabelSTOP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSTOP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSTOP, 0);
    lv_obj_set_y(ui_LabelSTOP, 45);
    lv_obj_set_align(ui_LabelSTOP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSTOP, "STOP");
    lv_obj_set_style_text_color(ui_LabelSTOP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSTOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_LabelChronoScreen4 = ui_LabelChronoScreen4;
    uic_LabelChronometreScreen4 = ui_LabelChronometreScreen4;
    uic_ButtonSTART = ui_ButtonSTART;
    uic_ButtonSTOP = ui_ButtonSTOP;

    chrono_init(ui_LabelChronoScreen2, uic_LabelChronoScreen4, ui_LabelChronoScreen1);

    lv_obj_add_event_cb(ui_ButtonSTART, start_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonSTOP, stop_btn_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonRESET, reset_btn_cb, LV_EVENT_CLICKED, NULL);


}
