// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Cercle1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen1Cercle1, 240);
    lv_obj_set_height(ui_Screen1Cercle1, 240);
    lv_obj_set_align(ui_Screen1Cercle1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Cercle1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Cercle1, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Cercle1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Cercle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKmHScreen2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelKmHScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKmHScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKmHScreen2, -28);
    lv_obj_set_y(ui_LabelKmHScreen2, -33);
    lv_obj_set_align(ui_LabelKmHScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKmHScreen2, "5");
    lv_obj_set_style_text_color(ui_LabelKmHScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelKmHScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKmHScreen2, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPasScreen2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPasScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPasScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPasScreen2, -30);
    lv_obj_set_y(ui_LabelPasScreen2, 28);
    lv_obj_set_align(ui_LabelPasScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPasScreen2, "856");
    lv_obj_set_style_text_color(ui_LabelPasScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPasScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPasScreen2, &ui_font_SFPRO48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2Point2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Point2, 10);
    lv_obj_set_height(ui_Screen2Point2, 10);
    lv_obj_set_x(ui_Screen2Point2, -15);
    lv_obj_set_y(ui_Screen2Point2, 90);
    lv_obj_set_align(ui_Screen2Point2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2Point2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen2Point1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Point1, 10);
    lv_obj_set_height(ui_Screen2Point1, 10);
    lv_obj_set_x(ui_Screen2Point1, -45);
    lv_obj_set_y(ui_Screen2Point1, 90);
    lv_obj_set_align(ui_Screen2Point1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2Point1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2Point1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2Point1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2Point3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Point3, 10);
    lv_obj_set_height(ui_Screen2Point3, 10);
    lv_obj_set_x(ui_Screen2Point3, 15);
    lv_obj_set_y(ui_Screen2Point3, 90);
    lv_obj_set_align(ui_Screen2Point3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2Point3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2Point3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2Point3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelKmH2Screen2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelKmH2Screen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKmH2Screen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKmH2Screen2, 49);
    lv_obj_set_y(ui_LabelKmH2Screen2, -28);
    lv_obj_set_align(ui_LabelKmH2Screen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKmH2Screen2, "m");
    lv_obj_set_style_text_color(ui_LabelKmH2Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelKmH2Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKmH2Screen2, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPas2Screen2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelPas2Screen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPas2Screen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelPas2Screen2, 54);
    lv_obj_set_y(ui_LabelPas2Screen2, 33);
    lv_obj_set_align(ui_LabelPas2Screen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPas2Screen2, "pas");
    lv_obj_set_style_text_color(ui_LabelPas2Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPas2Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPas2Screen2, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeScreen3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_LabelTimeScreen3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen3, 0);
    lv_obj_set_y(ui_LabelTimeScreen3, -100);
    lv_obj_set_align(ui_LabelTimeScreen3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen3, "15:08");
    lv_obj_set_style_text_color(ui_LabelTimeScreen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimeScreen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimeScreen3, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen2Point4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Screen2Point4, 10);
    lv_obj_set_height(ui_Screen2Point4, 10);
    lv_obj_set_x(ui_Screen2Point4, 45);
    lv_obj_set_y(ui_Screen2Point4, 90);
    lv_obj_set_align(ui_Screen2Point4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen2Point4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2Point4, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2Point4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_LabelKmHScreen2 = ui_LabelKmHScreen2;
    uic_LabelPasScreen2 = ui_LabelPasScreen2;
    uic_Screen2Point2 = ui_Screen2Point2;
    uic_Screen2Point1 = ui_Screen2Point1;
    uic_Screen2Point3 = ui_Screen2Point3;
    uic_LabelKmH2Screen2 = ui_LabelKmH2Screen2;
    uic_LabelPas2Screen2 = ui_LabelPas2Screen2;

}
