// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "../ui.h"
#include "rtc_callbacks.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Cercle3 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Screen1Cercle3, 240);
    lv_obj_set_height(ui_Screen1Cercle3, 240);
    lv_obj_set_align(ui_Screen1Cercle3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Cercle3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Cercle3, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Cercle3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Cercle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeureScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelHeureScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeureScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeureScreen5, -55);
    lv_obj_set_y(ui_LabelHeureScreen5, -45);
    lv_obj_set_align(ui_LabelHeureScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeureScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelHeureScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeureScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeureScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeure2Screen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelHeure2Screen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeure2Screen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeure2Screen5, -28);
    lv_obj_set_y(ui_LabelHeure2Screen5, -47);
    lv_obj_set_align(ui_LabelHeure2Screen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeure2Screen5, ":");
    lv_obj_set_style_text_color(ui_LabelHeure2Screen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeure2Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeure2Screen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinuteScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelMinuteScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinuteScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinuteScreen5, 0);
    lv_obj_set_y(ui_LabelMinuteScreen5, -44);
    lv_obj_set_align(ui_LabelMinuteScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMinuteScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelMinuteScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinuteScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinuteScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSecondeScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelSecondeScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSecondeScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSecondeScreen5, 55);
    lv_obj_set_y(ui_LabelSecondeScreen5, -43);
    lv_obj_set_align(ui_LabelSecondeScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSecondeScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelSecondeScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSecondeScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSecondeScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHeure2Screen1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelHeure2Screen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeure2Screen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeure2Screen1, 28);
    lv_obj_set_y(ui_LabelHeure2Screen1, -47);
    lv_obj_set_align(ui_LabelHeure2Screen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHeure2Screen1, ":");
    lv_obj_set_style_text_color(ui_LabelHeure2Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeure2Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeure2Screen1, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJourScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelJourScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJourScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJourScreen5, -55);
    lv_obj_set_y(ui_LabelJourScreen5, 45);
    lv_obj_set_align(ui_LabelJourScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJourScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelJourScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelJourScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJourScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelJour2Screen4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelJour2Screen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelJour2Screen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelJour2Screen4, -28);
    lv_obj_set_y(ui_LabelJour2Screen4, 43);
    lv_obj_set_align(ui_LabelJour2Screen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelJour2Screen4, "/");
    lv_obj_set_style_text_color(ui_LabelJour2Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelJour2Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelJour2Screen4, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMoisScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelMoisScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMoisScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMoisScreen5, 0);
    lv_obj_set_y(ui_LabelMoisScreen5, 45);
    lv_obj_set_align(ui_LabelMoisScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMoisScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelMoisScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMoisScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMoisScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMois2Screen4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelMois2Screen4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMois2Screen4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMois2Screen4, 28);
    lv_obj_set_y(ui_LabelMois2Screen4, 43);
    lv_obj_set_align(ui_LabelMois2Screen4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMois2Screen4, "/");
    lv_obj_set_style_text_color(ui_LabelMois2Screen4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMois2Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMois2Screen4, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAnneeScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelAnneeScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAnneeScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAnneeScreen5, 55);
    lv_obj_set_y(ui_LabelAnneeScreen5, 45);
    lv_obj_set_align(ui_LabelAnneeScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAnneeScreen5, "15");
    lv_obj_set_style_text_color(ui_LabelAnneeScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAnneeScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAnneeScreen5, &ui_font_SFPRO30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusHeure = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusHeure, 20);
    lv_obj_set_height(ui_ButtonPlusHeure, 20);
    lv_obj_set_x(ui_ButtonPlusHeure, -55);
    lv_obj_set_y(ui_ButtonPlusHeure, -73);
    lv_obj_set_align(ui_ButtonPlusHeure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusHeure, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusHeure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusHeure, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusHeure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusHeure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusHeure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeScreen5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_LabelTimeScreen5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen5, 0);
    lv_obj_set_y(ui_LabelTimeScreen5, -100);
    lv_obj_set_align(ui_LabelTimeScreen5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen5, "15:08");
    lv_obj_set_style_text_color(ui_LabelTimeScreen5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimeScreen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimeScreen5, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusMinute = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusMinute, 20);
    lv_obj_set_height(ui_ButtonPlusMinute, 20);
    lv_obj_set_x(ui_ButtonPlusMinute, 0);
    lv_obj_set_y(ui_ButtonPlusMinute, -73);
    lv_obj_set_align(ui_ButtonPlusMinute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusMinute, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusMinute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusMinute, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusSeconde = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusSeconde, 20);
    lv_obj_set_height(ui_ButtonPlusSeconde, 20);
    lv_obj_set_x(ui_ButtonPlusSeconde, 55);
    lv_obj_set_y(ui_ButtonPlusSeconde, -73);
    lv_obj_set_align(ui_ButtonPlusSeconde, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusSeconde, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusSeconde, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusSeconde, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusSeconde, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusSeconde, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusSeconde, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsHeure = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsHeure, 20);
    lv_obj_set_height(ui_ButtonMoinsHeure, 20);
    lv_obj_set_x(ui_ButtonMoinsHeure, -55);
    lv_obj_set_y(ui_ButtonMoinsHeure, -19);
    lv_obj_set_align(ui_ButtonMoinsHeure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsHeure, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsHeure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsHeure, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsHeure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsHeure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsHeure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsMinute = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsMinute, 20);
    lv_obj_set_height(ui_ButtonMoinsMinute, 20);
    lv_obj_set_x(ui_ButtonMoinsMinute, 0);
    lv_obj_set_y(ui_ButtonMoinsMinute, -19);
    lv_obj_set_align(ui_ButtonMoinsMinute, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsMinute, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsMinute, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsMinute, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsSeconde = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsSeconde, 20);
    lv_obj_set_height(ui_ButtonMoinsSeconde, 20);
    lv_obj_set_x(ui_ButtonMoinsSeconde, 55);
    lv_obj_set_y(ui_ButtonMoinsSeconde, -19);
    lv_obj_set_align(ui_ButtonMoinsSeconde, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsSeconde, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsSeconde, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsSeconde, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsSeconde, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsSeconde, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsSeconde, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusJour = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusJour, 20);
    lv_obj_set_height(ui_ButtonPlusJour, 20);
    lv_obj_set_x(ui_ButtonPlusJour, -55);
    lv_obj_set_y(ui_ButtonPlusJour, 15);
    lv_obj_set_align(ui_ButtonPlusJour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusJour, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusJour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusJour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusJour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusJour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusJour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusMois = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusMois, 20);
    lv_obj_set_height(ui_ButtonPlusMois, 20);
    lv_obj_set_x(ui_ButtonPlusMois, 0);
    lv_obj_set_y(ui_ButtonPlusMois, 16);
    lv_obj_set_align(ui_ButtonPlusMois, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusMois, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusMois, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusMois, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusMois, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusMois, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusMois, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPlusAnnee = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonPlusAnnee, 20);
    lv_obj_set_height(ui_ButtonPlusAnnee, 20);
    lv_obj_set_x(ui_ButtonPlusAnnee, 55);
    lv_obj_set_y(ui_ButtonPlusAnnee, 15);
    lv_obj_set_align(ui_ButtonPlusAnnee, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPlusAnnee, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonPlusAnnee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPlusAnnee, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPlusAnnee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPlusAnnee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonPlusAnnee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsJour = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsJour, 20);
    lv_obj_set_height(ui_ButtonMoinsJour, 20);
    lv_obj_set_x(ui_ButtonMoinsJour, -55);
    lv_obj_set_y(ui_ButtonMoinsJour, 71);
    lv_obj_set_align(ui_ButtonMoinsJour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsJour, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsJour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsJour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsJour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsJour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsJour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsMois = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsMois, 20);
    lv_obj_set_height(ui_ButtonMoinsMois, 20);
    lv_obj_set_x(ui_ButtonMoinsMois, 0);
    lv_obj_set_y(ui_ButtonMoinsMois, 71);
    lv_obj_set_align(ui_ButtonMoinsMois, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsMois, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsMois, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsMois, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsMois, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsMois, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsMois, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMoinsAnnee = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_ButtonMoinsAnnee, 20);
    lv_obj_set_height(ui_ButtonMoinsAnnee, 20);
    lv_obj_set_x(ui_ButtonMoinsAnnee, 55);
    lv_obj_set_y(ui_ButtonMoinsAnnee, 71);
    lv_obj_set_align(ui_ButtonMoinsAnnee, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMoinsAnnee, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonMoinsAnnee, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMoinsAnnee, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMoinsAnnee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMoinsAnnee, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ButtonMoinsAnnee, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus1, -55);
    lv_obj_set_y(ui_Plus1, -74);
    lv_obj_set_align(ui_Plus1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus1, "+");
    lv_obj_set_style_text_color(ui_Plus1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus1, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus2 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus2, 0);
    lv_obj_set_y(ui_Plus2, -74);
    lv_obj_set_align(ui_Plus2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus2, "+");
    lv_obj_set_style_text_color(ui_Plus2, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus2, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus3 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus3, 55);
    lv_obj_set_y(ui_Plus3, -74);
    lv_obj_set_align(ui_Plus3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus3, "+");
    lv_obj_set_style_text_color(ui_Plus3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus3, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus4, -55);
    lv_obj_set_y(ui_Plus4, 14);
    lv_obj_set_align(ui_Plus4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus4, "+");
    lv_obj_set_style_text_color(ui_Plus4, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus4, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus5, 0);
    lv_obj_set_y(ui_Plus5, 15);
    lv_obj_set_align(ui_Plus5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus5, "+");
    lv_obj_set_style_text_color(ui_Plus5, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus5, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus6 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Plus6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Plus6, 55);
    lv_obj_set_y(ui_Plus6, 14);
    lv_obj_set_align(ui_Plus6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus6, "+");
    lv_obj_set_style_text_color(ui_Plus6, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus6, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins1 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins1, -55);
    lv_obj_set_y(ui_Moins1, -20);
    lv_obj_set_align(ui_Moins1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins1, "-");
    lv_obj_set_style_text_color(ui_Moins1, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins1, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins2 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins2, 0);
    lv_obj_set_y(ui_Moins2, -20);
    lv_obj_set_align(ui_Moins2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins2, "-");
    lv_obj_set_style_text_color(ui_Moins2, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins2, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins3 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins3, 55);
    lv_obj_set_y(ui_Moins3, -20);
    lv_obj_set_align(ui_Moins3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins3, "-");
    lv_obj_set_style_text_color(ui_Moins3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins3, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins4 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins4, -55);
    lv_obj_set_y(ui_Moins4, 70);
    lv_obj_set_align(ui_Moins4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins4, "-");
    lv_obj_set_style_text_color(ui_Moins4, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins4, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins5 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins5, 0);
    lv_obj_set_y(ui_Moins5, 70);
    lv_obj_set_align(ui_Moins5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins5, "-");
    lv_obj_set_style_text_color(ui_Moins5, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins5, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Moins6 = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_Moins6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Moins6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Moins6, 55);
    lv_obj_set_y(ui_Moins6, 70);
    lv_obj_set_align(ui_Moins6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Moins6, "-");
    lv_obj_set_style_text_color(ui_Moins6, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Moins6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Moins6, &ui_font_SFPRO25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_Button4, 30);
    lv_obj_set_height(ui_Button4, 25);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 100);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image7, &ui_img_1270785427);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, 100);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Screen5 = ui_Screen5;
    uic_LabelHeureScreen5 = ui_LabelHeureScreen5;
    uic_LabelHeure2Screen5 = ui_LabelHeure2Screen5;
    uic_LabelMinuteScreen5 = ui_LabelMinuteScreen5;
    uic_LabelSecondeScreen5 = ui_LabelSecondeScreen5;
    uic_LabelHeure2Screen1 = ui_LabelHeure2Screen1;
    uic_LabelJourScreen5 = ui_LabelJourScreen5;
    uic_LabelJour2Screen4 = ui_LabelJour2Screen4;
    uic_LabelMoisScreen5 = ui_LabelMoisScreen5;
    uic_LabelMois2Screen4 = ui_LabelMois2Screen4;
    uic_LabelAnneeScreen5 = ui_LabelAnneeScreen5;
    uic_ButtonPlusHeure = ui_ButtonPlusHeure;
    uic_ButtonPlusMinute = ui_ButtonPlusMinute;
    uic_ButtonPlusSeconde = ui_ButtonPlusSeconde;
    uic_ButtonMoinsHeure = ui_ButtonMoinsHeure;
    uic_ButtonMoinsMinute = ui_ButtonMoinsMinute;
    uic_ButtonMoinsSeconde = ui_ButtonMoinsSeconde;
    uic_ButtonPlusJour = ui_ButtonPlusJour;
    uic_ButtonPlusMois = ui_ButtonPlusMois;
    uic_ButtonPlusAnnee = ui_ButtonPlusAnnee;
    uic_ButtonMoinsJour = ui_ButtonMoinsJour;
    uic_ButtonMoinsMois = ui_ButtonMoinsMois;
    uic_ButtonMoinsAnnee = ui_ButtonMoinsAnnee;
    uic_Plus1 = ui_Plus1;
    uic_Moins1 = ui_Moins1;

    // Callbacks boutons HEURE / MINUTE / SECONDE
    lv_obj_add_event_cb(ui_ButtonPlusHeure, hour_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsHeure, hour_minus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonPlusMinute, minute_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsMinute, minute_minus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonPlusSeconde, second_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsSeconde, second_minus_cb, LV_EVENT_CLICKED, NULL);

    // Callbacks boutons JOUR / MOIS / ANNÉE
    lv_obj_add_event_cb(ui_ButtonPlusJour, day_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsJour, day_minus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonPlusMois, month_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsMois, month_minus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonPlusAnnee, year_plus_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ButtonMoinsAnnee, year_minus_cb, LV_EVENT_CLICKED, NULL);
    
    // Callback Bouton Home
    lv_obj_add_event_cb(ui_Button4, home_cb, LV_EVENT_CLICKED, NULL);
}   
