// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: led_switch - Copie

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Cercle = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Cercle, 240);
    lv_obj_set_height(ui_Screen1Cercle, 240);
    lv_obj_set_x(ui_Screen1Cercle, 0);
    lv_obj_set_y(ui_Screen1Cercle, -1);
    lv_obj_set_align(ui_Screen1Cercle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Cercle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Screen1Cercle, 10000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Screen1Cercle, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Cercle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempScreen1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTempScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempScreen1, -10);
    lv_obj_set_y(ui_LabelTempScreen1, -95);
    lv_obj_set_align(ui_LabelTempScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempScreen1, "18");
    lv_obj_set_style_text_color(ui_LabelTempScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempScreen1, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTempCScreen1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTempCScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTempCScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTempCScreen1, 20);
    lv_obj_set_y(ui_LabelTempCScreen1, -95);
    lv_obj_set_align(ui_LabelTempCScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTempCScreen1, "°C");
    lv_obj_set_style_text_color(ui_LabelTempCScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTempCScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTempCScreen1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTimeScreen1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTimeScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeScreen1, 0);
    lv_obj_set_y(ui_LabelTimeScreen1, -23);
    lv_obj_set_align(ui_LabelTimeScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTimeScreen1, "15:08");
    lv_obj_set_style_text_color(ui_LabelTimeScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTimeScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTimeScreen1, &ui_font_SFPRO72, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDateScreen1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDateScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDateScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDateScreen1, 0);
    lv_obj_set_y(ui_LabelDateScreen1, 23);
    lv_obj_set_align(ui_LabelDateScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDateScreen1, "24/03/25");
    lv_obj_set_style_text_color(ui_LabelDateScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDateScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDateScreen1, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumScreen1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHumScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHumScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHumScreen1, 0);
    lv_obj_set_y(ui_LabelHumScreen1, 64);
    lv_obj_set_align(ui_LabelHumScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumScreen1, "Hum");
    lv_obj_set_style_text_color(ui_LabelHumScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHumScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHumScreen1, &ui_font_SFPRO20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1Point1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Point1, 10);
    lv_obj_set_height(ui_Screen1Point1, 10);
    lv_obj_set_x(ui_Screen1Point1, -45);
    lv_obj_set_y(ui_Screen1Point1, 90);
    lv_obj_set_align(ui_Screen1Point1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Point1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Screen1Point2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Point2, 10);
    lv_obj_set_height(ui_Screen1Point2, 10);
    lv_obj_set_x(ui_Screen1Point2, -15);
    lv_obj_set_y(ui_Screen1Point2, 90);
    lv_obj_set_align(ui_Screen1Point2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Point2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1Point2, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Point2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Screen1Point3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Point3, 10);
    lv_obj_set_height(ui_Screen1Point3, 10);
    lv_obj_set_x(ui_Screen1Point3, 15);
    lv_obj_set_y(ui_Screen1Point3, 90);
    lv_obj_set_align(ui_Screen1Point3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Point3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1Point3, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Point3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_Screen1);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_parametre1_30x30_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_parametre1_30x30_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 30);
    lv_obj_set_height(ui_ImgButton2, 30);
    lv_obj_set_x(ui_ImgButton2, -60);
    lv_obj_set_y(ui_ImgButton2, 24);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_Screen1Point4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Screen1Point4, 10);
    lv_obj_set_height(ui_Screen1Point4, 10);
    lv_obj_set_x(ui_Screen1Point4, 45);
    lv_obj_set_y(ui_Screen1Point4, 90);
    lv_obj_set_align(ui_Screen1Point4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Screen1Point4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1Point4, lv_color_hex(0x1E1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1Point4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen1 = ui_Screen1;
    uic_Screen1Cercle = ui_Screen1Cercle;
    uic_LabelTempScreen1 = ui_LabelTempScreen1;
    uic_LabelTempCScreen1 = ui_LabelTempCScreen1;
    uic_LabelTimeScreen1 = ui_LabelTimeScreen1;
    uic_LabelDateScreen1 = ui_LabelDateScreen1;
    uic_LabelHumScreen1 = ui_LabelHumScreen1;
    uic_Screen1Point1 = ui_Screen1Point1;

}
